### ISSUE TITLE
Convention Section

### ISSUE THREAD

**Issue by thomas-lamiaux** [Zimmi48/platform-docs#13]
In the tutorial for Equations, I have used the following coqdoc syntax :
```
* 1. ...
** 1.1 ... 
*** 1.1.1 ...
```
I have noticed #11 uses
```
** 1. ...
*** 1.1 ...
```
should we fix a convention so that all files look the same once they'll be a web interface ?

**Comment by Villetaneuse** [comment]
The `coqdoc` output of `(** * A single star title *)` is really big.
As far as I know, it's only used for the title of the document.

**Comment by thomas-lamiaux** [comment]
@Villetaneuse does it look big too with JsCoq ?

**Comment by Villetaneuse** [comment]
It really depends on your `css`, but I'm quite sure it really semantically means "title of the document", a bit like one `#` header in `md` is for the title.

**Comment by thomas-lamiaux** [comment]
Ok, I'll add it in the guidelines
